"""Execution tests for documentation generated by the Dokka rule."""

load("@bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("@bazel_lib//lib:diff_test.bzl", "diff_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

def generated_docs_test_suite(name):
    """Defines tests for single-module generated documentation.

    Args:
        name: Base name and tag for the generated tests.
    """
    copy_to_directory(
        name = name + "_actual_gfm_markdown",
        srcs = ["//tests/fixtures/generated_docs:gfm_docs"],
        include_srcs_patterns = [
            "*.md",
            "**/*.md",
        ],
        replace_prefixes = {
            "-example -a-p-i": "example-api",
            "-example -a-p-i/com.example/-bar": "example-api/com.example/bar",
            "-example -a-p-i/com.example/-bar/-bar.md": "example-api/com.example/bar/bar.md",
            "-example -a-p-i/com.example/-foo": "example-api/com.example/foo",
            "-example -a-p-i/com.example/-foo/-foo.md": "example-api/com.example/foo/foo.md",
        },
        root_paths = ["tests/fixtures/generated_docs/gfm_docs"],
    )

    diff_test(
        name = name + "_gfm_diff",
        failure_message = "Generated GFM documentation differs from its checked-in fixtures.",
        file1 = "//tests/fixtures/generated_docs:expected_gfm_markdown",
        file2 = ":" + name + "_actual_gfm_markdown",
        tags = [name],
    )

    diff_test(
        name = name + "_dependencies_diff",
        failure_message = "Dokka did not resolve the API exposed by its compiled dependency.",
        file1 = "//tests/fixtures/dependencies:expected_markdown",
        file2 = "//tests/fixtures/dependencies:actual_markdown",
        tags = [name],
    )

    sh_test(
        name = name + "_formats",
        srcs = ["generated_docs_test.sh"],
        args = [
            "$(rlocationpath //tests/fixtures/generated_docs:gfm_docs)",
            "$(rlocationpath //tests/fixtures/generated_docs:html_docs)",
            "$(rlocationpath //tests/fixtures/generated_docs:javadoc_docs)",
        ],
        data = [
            "//tests/fixtures/generated_docs:gfm_docs",
            "//tests/fixtures/generated_docs:html_docs",
            "//tests/fixtures/generated_docs:javadoc_docs",
        ],
        deps = ["@bazel_tools//tools/bash/runfiles"],
        tags = [name],
    )

    native.test_suite(
        name = name,
        tags = [name],
    )
