load("@bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("//dokka:defs.bzl", "dokka", "dokka_config")
load("//tests/fixtures:common.bzl", "FIXTURE_TAGS")

package(default_visibility = ["//tests:__subpackages__"])

kt_jvm_library(
    name = "dependency",
    srcs = ["Dependency.kt"],
    neverlink = True,
    tags = FIXTURE_TAGS,
)

dokka_config(
    name = "config",
    no_jdk_link = True,
    no_stdlib_link = True,
    tags = FIXTURE_TAGS,
)

dokka(
    name = "docs",
    srcs = ["UsesDependency.kt"],
    config = ":config",
    format = "gfm",
    module_name = "Dependency API",
    tags = FIXTURE_TAGS,
    deps = [":dependency"],
)

copy_to_directory(
    name = "actual_markdown",
    srcs = [":docs"],
    include_srcs_patterns = ["**/-uses-dependency/index.md"],
    replace_prefixes = {
        "-dependency -a-p-i/com.example/-uses-dependency": "uses-dependency",
    },
    root_paths = ["tests/fixtures/dependencies/docs"],
    tags = FIXTURE_TAGS,
)

copy_to_directory(
    name = "expected_markdown",
    srcs = glob(["expected/**/*.md"]),
    root_paths = ["tests/fixtures/dependencies/expected"],
    tags = FIXTURE_TAGS,
)
