load("//dokka:defs.bzl", "dokka_config", "dokka_generator", "dokka_toolchain")

package(default_visibility = ["//visibility:public"])

toolchain_type(name = "toolchain_type")

dokka_config(
    name = "default_config",
)

dokka_generator(
    name = "dokka_generator",
    dokka_cli = "@rules_dokka_dependencies//:org_jetbrains_dokka_dokka_cli",
    jackson_databind = "@rules_dokka_dependencies//:com_fasterxml_jackson_core_jackson_databind",
)

dokka_toolchain(
    name = "default_toolchain",
    default_config = ":default_config",
    generator = ":dokka_generator",
    gfm_plugins = [
        "@rules_dokka_dependencies//:org_freemarker_freemarker",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_analysis_kotlin_symbols",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_dokka_base",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_gfm_plugin",
        "@rules_dokka_dependencies//:org_jetbrains_kotlinx_kotlinx_html_jvm",
    ],
    html_plugins = [
        "@rules_dokka_dependencies//:org_freemarker_freemarker",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_analysis_kotlin_symbols",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_dokka_base",
        "@rules_dokka_dependencies//:org_jetbrains_kotlinx_kotlinx_html_jvm",
    ],
    javadoc_plugins = [
        "@rules_dokka_dependencies//:com_soywiz_korlibs_korte_korte_jvm",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_analysis_kotlin_symbols",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_dokka_base",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_javadoc_plugin",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_kotlin_as_java_plugin",
    ],
    multi_module_plugins = [
        "@rules_dokka_dependencies//:org_jetbrains_dokka_all_modules_page_plugin",
    ],
)
