load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

package(default_visibility = ["//dokka:__subpackages__"])

exports_files(
    ["DokkaGeneratorRunner.kt"],
    visibility = ["//visibility:public"],
)

kt_jvm_binary(
    name = "dokka_generator",
    srcs = ["DokkaGeneratorRunner.kt"],
    main_class = "rules.dokka.DokkaGeneratorRunner",
    visibility = ["//dokka:__pkg__"],
    deps = [
        "@rules_dokka_dependencies//:com_fasterxml_jackson_core_jackson_databind",
        "@rules_dokka_dependencies//:org_jetbrains_dokka_dokka_cli",
    ],
)
