name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: "Install the JDK"
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "11.0.5"
      - name: Install buildifier
        run: |
          curl --location --fail "https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier" --output /tmp/bazel
          bazel --version
          chmod +x /tmp/bazel && echo "/tmp/" >> $GITHUB_PATH
          bazel --version
      - name: "Linting"
        run: $GITHUB_WORKSPACE/bin/buildifier -mode check -lint warn -r .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: "Install the JDK"
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "11.0.5"
      - name: Install bazelisk
        run: |
          curl --location --fail "https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier" --output /tmp/bazel
          bazel --version
          chmod +x /tmp/bazel && echo "/tmp/" >> $GITHUB_PATH
          bazel --version
      - name: "Running unit tests"
        run: $GITHUB_WORKSPACE/bin/bazel test //tests:tests
      - name: "Running integrations"
        run: $GITHUB_WORKSPACE/bin/bazel test //tests/integration:does_build
