name: main

on:
  push:
    branches:
      - main
  pull_request:

env:
  VERSION_BAZELISK: "1.6.1"
  VERSION_BUILDIFIER: "3.4.1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: "Install the JDK"
        uses: actions/setup-java@v1.3.0
        with:
          java-version: "11.0.5"
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v${VERSION_BAZELISK}/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: "Running unit tests"
        run: bazel test //tests:tests
      - name: "Running integrations"
        run: bazel build //tests/integration:does_build
